---
- name: Add Traefik middleware
  ansible.builtin.template:
    src: "{{ playbook_dir }}/traefik/middleware.yml.j2"
    dest: "{{ traefik_appdata_dir }}/config/middleware.yml"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: 0644

- name: Add Traefik routes and services
  ansible.builtin.template:
    src: "{{ playbook_dir }}/traefik/{{ container.name | lower }}.yml.j2"
    dest: "{{ traefik_appdata_dir }}/config/{{ container.name | lower }}.yml"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: 0644
  vars:
    service_ip: "{{ traefik_server_ip }}"
  when: container.state != 'absent' and container.frontend
  loop: "{{ podman_containers }}"

- name: Remove Traefik routes and services
  ansible.builtin.file:
    path: "{{ traefik_appdata_dir }}/config/{{ container.name | lower }}.yml"
    state: absent
  when: container.state == 'absent'
  loop: "{{ podman_containers }}"
